# Generated by Django 5.0.7 on 2024-07-20 08:38

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_story', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('mission', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('vision', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('values', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=2000, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('subject', models.CharField(blank=True, max_length=2000, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=2000, null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('sort_name', models.CharField(blank=True, max_length=10, null=True)),
                ('image', models.ImageField(blank=True, default='/country/image/placeholder.png', null=True, upload_to='country/image')),
                ('flag', models.ImageField(blank=True, default='/country/flag/placeholder.png', null=True, upload_to='country/flag')),
                ('description', models.TextField(default='null')),
                ('details_and_scholarship', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('job_and_proposal', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('FAQ', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('visa_requirement', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='CountryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=2000, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DualQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='/page/image/placeholder.png', null=True, upload_to='dualQualification/')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('image', models.ImageField(blank=True, default='/faculty/placeholder.png', null=True, upload_to='faculty/')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Faculty',
                'verbose_name_plural': 'Faculties',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('order', models.IntegerField(default=1)),
                ('offers', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OurQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('order', models.IntegerField(default=0)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='/OurQualification/placeholder.png', null=True, upload_to='OurQualification/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('courses_list', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('description', models.TextField(default='null')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QualificationApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('nic', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AbroadApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.country')),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.countrycategory'),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, default='/course/placeholder.png', null=True, upload_to='courses/')),
                ('course_credit', models.CharField(blank=True, max_length=200, null=True)),
                ('class_on', models.CharField(blank=True, max_length=200, null=True)),
                ('overview', ckeditor.fields.RichTextField(default='')),
                ('requirements', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('units', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('popular', models.BooleanField(default=False)),
                ('duration', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('show_in_header', models.BooleanField(default=False)),
                ('show_in_faculty', models.BooleanField(default=False)),
                ('show_in_qualification', models.BooleanField(default=False)),
                ('show_in_footer', models.BooleanField(default=False)),
                ('ebrowcher', models.FileField(blank=True, null=True, upload_to='browcher/')),
                ('gif_logo', models.ImageField(blank=True, null=True, upload_to='git/logo/')),
                ('f_title', models.CharField(blank=True, default='Graduate Diploma', max_length=20, null=True)),
                ('f_1_name', models.CharField(blank=True, default='Level 6', max_length=20, null=True)),
                ('f_2_name', models.CharField(blank=True, default='120 credits', max_length=20, null=True)),
                ('f_gif_logo1', models.ImageField(blank=True, null=True, upload_to='git/logo/')),
                ('f_gif_logo2', models.ImageField(blank=True, null=True, upload_to='git/logo/')),
                ('s_top', models.CharField(blank=True, default='Up to', max_length=20, null=True)),
                ('s_center', models.CharField(blank=True, default='56%', max_length=20, null=True)),
                ('s_bottom', models.CharField(blank=True, default='Scholarship', max_length=20, null=True)),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.faculty')),
                ('programe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.level')),
                ('qualification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.ourqualification')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('answer', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.country')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
            },
        ),
        migrations.CreateModel(
            name='DualQualificationCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, default='/course/placeholder.png', null=True, upload_to='courses/')),
                ('course_credit', models.CharField(blank=True, max_length=200, null=True)),
                ('class_on', models.CharField(blank=True, max_length=200, null=True)),
                ('overview', ckeditor.fields.RichTextField(default='')),
                ('requirements', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('units', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('popular', models.BooleanField(default=False)),
                ('duration', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.course')),
                ('dual_qualification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.dualqualification')),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.faculty')),
                ('programe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.level')),
                ('qualification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.ourqualification')),
            ],
        ),
        migrations.CreateModel(
            name='PageCoverImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='/page/image/placeholder.png', null=True, upload_to='page/')),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.page')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.country')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.course')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.page')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.university')),
            ],
        ),
    ]
