# Generated by Django 5.0.7 on 2024-07-20 05:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='visa_requirement',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ourqualification',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
