# Generated by Django 5.0.6 on 2024-06-10 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='order',
            field=models.IntegerField(default=1, max_length=140),
        ),
    ]
