# Generated by Django 5.0.6 on 2024-06-11 16:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='overview',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
