# Generated by Django 5.0.6 on 2024-06-10 09:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_level_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='FAQ',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='level',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
