# Generated by Django 5.0.7 on 2024-07-20 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_country_description_country_visa_requirement_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ourqualification',
            old_name='courses_list',
            new_name='about',
        ),
        migrations.RemoveField(
            model_name='country',
            name='description',
        ),
        migrations.RemoveField(
            model_name='country',
            name='visa_requirement',
        ),
        migrations.RemoveField(
            model_name='ourqualification',
            name='description',
        ),
    ]
