# Generated by Django 5.0.6 on 2024-06-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_course_overview'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='sort_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
