# Generated by Django 5.0.6 on 2024-06-20 06:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_about_mission_alter_about_our_story_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='FAQ',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
