# Generated by Django 5.0.6 on 2024-05-18 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_unit_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classon',
            options={'verbose_name': 'Class on', 'verbose_name_plural': 'Class on'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name': 'Faculty', 'verbose_name_plural': 'Faculties'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQ'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='qualification_approval',
        ),
        migrations.AddField(
            model_name='course',
            name='qualification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.ourqualification'),
        ),
    ]
