# Generated by Django 5.0.6 on 2024-05-18 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_classon_options_alter_country_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseQualification',
        ),
    ]
