# Generated by Django 5.0.7 on 2024-07-24 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_dualqualificationcourse_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='dualqualification',
            name='brochure',
            field=models.FileField(blank=True, null=True, upload_to='brochure/'),
        ),
    ]
