# Generated by Django 5.0.6 on 2024-06-22 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_testimonial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='programe',
        ),
    ]
