# Generated by Django 5.0.6 on 2024-05-18 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_delete_coursequalification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='class_on',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='ClassOn',
        ),
    ]
