# Generated by Django 5.0.6 on 2024-06-23 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_testimonial_programe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='position',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.course'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.page'),
        ),
    ]
