# Generated by Django 5.0.7 on 2024-08-02 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_card_card_course_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.page'),
        ),
    ]
