# Generated by Django 5.0.6 on 2024-05-20 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_courselevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='programe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.level'),
        ),
        migrations.DeleteModel(
            name='CourseLevel',
        ),
    ]
