# Generated by Django 5.0.7 on 2024-08-06 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_event_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='dualqualificationcourse',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.card'),
        ),
    ]
