# Generated by Django 5.0.6 on 2024-07-02 17:13

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_university_testimonial_university'),
    ]

    operations = [
        migrations.CreateModel(
            name='DualQualificationCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, default='/course/placeholder.png', null=True, upload_to='courses/')),
                ('course_credit', models.CharField(blank=True, max_length=200, null=True)),
                ('class_on', models.CharField(blank=True, max_length=200, null=True)),
                ('overview', ckeditor.fields.RichTextField(default='')),
                ('requirements', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('units', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('popular', models.BooleanField(default=False)),
                ('duration', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.course')),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.faculty')),
                ('programe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.level')),
                ('qualification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.ourqualification')),
            ],
        ),
    ]
