# Generated by Django 5.0.6 on 2024-07-07 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_dualqualificationcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='ebrowcher',
            field=models.FileField(blank=True, null=True, upload_to='browcher/'),
        ),
    ]
