# Generated by Django 5.0.6 on 2024-05-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_country_slug_course_slug_faculty_slug_level_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, default='/course/placeholder.png', null=True, upload_to=''),
        ),
    ]
