# Generated by Django 5.0.6 on 2024-07-07 13:05

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_course_ebrowcher'),
    ]

    operations = [
        migrations.CreateModel(
            name='DualQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='/page/image/placeholder.png', null=True, upload_to='dualQualification/')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='dualqualificationcourse',
            name='dual_qualification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.dualqualification'),
        ),
    ]
