# Generated by Django 5.0.6 on 2024-05-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='credit_count',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
