# Generated by Django 5.0.6 on 2024-07-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_dualqualification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dualqualification',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dualqualification',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
