# Generated by Django 5.0.6 on 2024-07-08 01:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_dualqualification_name_dualqualification_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourqualification',
            name='courses_list',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
