# Generated by Django 5.0.6 on 2024-07-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_ourqualification_courses_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='f_1_name',
            field=models.CharField(blank=True, default='Level 6', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='f_2_name',
            field=models.CharField(blank=True, default='120 credits', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='f_gif_logo1',
            field=models.ImageField(blank=True, null=True, upload_to='git/logo/'),
        ),
        migrations.AddField(
            model_name='course',
            name='f_gif_logo2',
            field=models.ImageField(blank=True, null=True, upload_to='git/logo/'),
        ),
        migrations.AddField(
            model_name='course',
            name='f_title',
            field=models.CharField(blank=True, default='Graduate Diploma', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='s_bottom',
            field=models.CharField(blank=True, default='Scholarship', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='s_center',
            field=models.CharField(blank=True, default='56%', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='s_top',
            field=models.CharField(blank=True, default='Up to', max_length=20, null=True),
        ),
    ]
