# Generated by Django 5.0.6 on 2024-07-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_course_f_1_name_course_f_2_name_course_f_gif_logo1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='gif_logo',
            field=models.ImageField(blank=True, null=True, upload_to='git/logo/'),
        ),
    ]
