# Generated by Django 5.0.6 on 2024-07-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_course_gif_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='show_in_faculty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='show_in_footer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='show_in_header',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='show_in_qualification',
            field=models.BooleanField(default=False),
        ),
    ]
