# Generated by Django 5.0.6 on 2024-07-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_course_show_in_faculty_course_show_in_footer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='credit_slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
