# Generated by Django 5.0.6 on 2024-07-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_course_credit_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credit_slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
