# Generated by Django 5.0.6 on 2024-07-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_generate_slugs'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=2000, null=True)),
                ('nic', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
            ],
        ),
    ]
