# Generated by Django 5.0.6 on 2024-07-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_studentverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(blank=True, max_length=2000, null=True)),
                ('date', models.DateField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
