# Generated by Django 5.0.6 on 2024-07-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentverification',
            name='nic',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
