# Generated by Django 5.0.6 on 2024-07-14 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_course_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='credit_slug',
        ),
    ]
