# Generated by Django 5.0.6 on 2024-07-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_remove_course_credit_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, default='/course/placeholder.png', null=True, upload_to='courses/banner/'),
        ),
    ]
