# Generated by Django 5.0.6 on 2024-07-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_alter_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='banner',
            field=models.ImageField(blank=True, default='/course/placeholder.png', null=True, upload_to='courses/banner/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, default='/course/placeholder.png', null=True, upload_to='courses/'),
        ),
    ]
